Repository ConnectAI-E/GitMaya, pull requests merged in 2024-01, with the labels that each got.

#102 Freeziyou 0122
  server/tasks/github/github.py
  server/tasks/lark/issue.py
  server/utils/github/organization.py
  server/utils/lark/chat_manual.py
  server/utils/lark/manage_manual.py
  server/utils/lark/repo_manual.py
Labels: bug

#109 feat: lark sdk bot add redis storage
  server/routes/lark.py
  server/tasks/github/issue.py
  server/tasks/lark/base.py
  server/tasks/lark/chat.py
  server/tasks/lark/lark.py
  server/tasks/lark/manage.py
  server/utils/redis.py
Labels: bug, enhancement

#126 hotfix: del attr
  pdm.lock
  pyproject.toml
  requirements.txt
Labels: bug

#133 Add create issue with description
  server/tasks/lark/chat.py
  server/utils/lark/parser.py
  server/utils/lark/post_message.py
Labels: bug

#135 hotfix: merge code from test server
  server/routes/lark.py
Labels: bug

#139 Fix repo info update
  server/routes/github.py
  server/tasks/github/issue.py
  server/tasks/github/repo.py
  server/utils/github/model.py
Labels: bug

#140 Add close with comment
  server/tasks/__init__.py
  server/utils/lark/parser.py
Labels: enhancement

#148 Feature lloyd 20240125
  server/app.py
  server/routes/team.py
Labels: feature

#144 Fix timezone
  server/celery_app.py
Labels: bug

#142 Fix homepage
  server/tasks/lark/manage.py
  server/tasks/lark/repo.py
  server/utils/lark/repo_info.py
Labels: bug

#154 fix label
  server/tasks/lark/chat.py
  server/utils/lark/parser.py
Labels: bug

#166 add change-assignee-with-at
  server/tasks/lark/issue.py
Labels: enhancement

#164 Fix at user
  .github/workflows/docker-image.yml
  deploy/Dockerfile.proxy.saas
  server/tasks/lark/issue.py
  server/utils/lark/parser.py
  server/utils/redis.py
Labels: bug
